language: csharp
solution: XShell.sln
install:
 - nuget restore XShell.sln
 - nuget install NUnit.Console -Version 3.10.0 -OutputDirectory testrunner
mono:
  - latest
before_script:
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
 - sleep 3 # give xvfb some time to start
script:
 - msbuild /p:Configuration=Release XShell.sln
 - mono ./testrunner/NUnit.ConsoleRunner.3.10.0/tools/nunit3-console.exe ./XShell.Tests/bin/Release/net472/XShell.Tests.dll